########################################
######## GOFIGURE CONFIGURATION ########
########################################

# Key = What will appear in the selection menu
# Value = Command that will be executed

i3wm: $EDITOR $HOME/.config/i3/config
lf: $EDITOR $HOME/.config/lf/lfrc
kitty: $EDITOR $HOME/.config/kitty/kitty.conf
picom: $EDITOR $HOME/.config/picom/picom.conf
fish: $EDITOR $HOME/.config/fish/config.fish
polybar: $EDITOR $HOME/.config/polybar/config
rofi: $EDITOR $HOME/.config/rofi/config.rasi
nvim: lf $HOME/.config/nvim
External_Drives: lf /media/$(ls /media)
Trash: lf /home/alan/.local/share/Trash
